### ISSUE TITLE
Further enlarge version bounds for elm-community/list-extra. Pretty please?

### ISSUE THREAD

**Issue by Birowsky** [Gizra/elm-dictlist#17]
Just hit this issue:

![image](https://user-images.githubusercontent.com/3199950/35481927-7e0b9476-042d-11e8-8a48-0e9dfc94d091.png)

But I need you both :}

**Comment by Birowsky** [comment]
Just click the button:
https://github.com/Gizra/elm-dictlist/pull/18

**Comment by rgrempel** [comment]
Thanks!

I'll push a new version out later today -- I might have a bug fix to include as well.

**Comment by rgrempel** [comment]
Version 2.1.1 is now published.
