### ISSUE TITLE
Elm 0.17 vs. 0.18

### ISSUE THREAD

**Issue by rgrempel** [Gizra/elm-dictlist#2]
I started this as an Elm 0.17 project, because we're extracting this from an internal project that uses Elm 0.17 -- so we'll want to use it with Elm 0.17.

However, for publishing it, it probably makes more sense to switch to Elm 0.18? I suppose I could maintain a separate branch for Elm 0.17 that we could arrange to install for the original internal project in one way or another.

**Comment by rgrempel** [comment]
I don't think it's possible to maintain parallel 0.17 and 0.18 versions in the Elm package repository. However, we could arrange to install a 0.17 branch internally, if we switched to 0.18 for publishing.

**Comment by amitaibu** [comment]
>  for publishing it, it probably makes more sense to switch to Elm 0.18?

Yeah, I also think it should be 0.18

**Comment by rgrempel** [comment]
I've done the Elm 0.18 update in 034e090.

For back-compat, I've isolated anything that is incompatible between Elm 0.18 and 0.17 in `DictList.Compat`. That way, we can copy the `DictList` code into internal Elm 0.17 projects, and simply import a different `DictList.Compat`. That should make it pretty easy to keep things in sync.
