### ISSUE TITLE
Publish version 1.0

### ISSUE THREAD

**Issue by rgrempel** [Gizra/elm-dictlist#5]
Here's a checklist of things I'd like to finish before version 1.0:

- [x] Implement all the core `Dict` functions
- [x] Implement all the core `List` functions that make sense here
- [x] Pass the core `Dict` tests
- [x] Pass the core `List` tests
- [ ] Write tests for uniquely `DictList` behaviours
- [x] Review documentation

I expect to leave #3 and #4 for post-1.0.

**Comment by amitaibu** [comment]
Would be great to get this soon, as we have another 0.18 project that we'd like to use this lib. And a blog post to follow it :)

**Comment by rgrempel** [comment]
I've done a round of editing for the documentation. So, what's left is finishing the tests.

I've been writing a couple of tests every day for a little while -- would probably take another couple of weeks at that rate. Or, we could publish as-is, and fix anything which further tests find. Or, I could spend a day finishing all the tests.

**Comment by amitaibu** [comment]
I think we can already publish, and then add the rest of the tests incrementally.

**Comment by rgrempel** [comment]
Done!

http://package.elm-lang.org/packages/Gizra/elm-dictlist/1.0.0/DictList
